// POLICY.md section 8.3 step 2: body shape. Every failure here is
// INVALID_REQUEST — the caller maps null to that one code. Field rules with
// their own codes run later (steps 3 to 6); this module checks presence,
// key sets and JSON types only, per section 2.3.
//
// The raw body object never flows past this module: the return value is
// rebuilt field by field, so no unknown client key has a path to the hash
// (section 3.1).
import type { ValidatedPolicyInput } from "./policy.ts";

// Section 10.1: a uuid in lowercase hyphenated form, generated by the
// client. The spec does not constrain the client's generator, so no version
// nibble here — the v4 rule applies only to server-assigned requirement ids
// (section 2.2). A v4-only regex would reject keys the spec accepts.
// Exported: section 8.5 step 2 checks :id against the same form.
export const UUID_FORM =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

// Section 2.3: integer fields accept only JSON numbers that are integers in
// the safe range (SPEC.md section 1.3). Number.isSafeInteger is exactly that
// test; fractions, NaN, infinities and out-of-range magnitudes all fail it.
function isSafeInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasExactKeys(
  obj: Record<string, unknown>,
  required: readonly string[],
  optional: readonly string[] = [],
): boolean {
  const keys = Object.keys(obj);
  for (const key of keys) {
    if (!required.includes(key) && !optional.includes(key)) return false;
  }
  return required.every((key) => keys.includes(key));
}

const BODY_KEYS = ["idempotency_key", "title", "category", "policy"] as const;

const POLICY_REQUIRED_KEYS = [
  "acceptance_window_seconds",
  "attester_pubkey",
  "capture_radius_m",
  "challenge_window_seconds",
  "completion_window_seconds",
  "evidence_requirements",
  "lat",
  "lon",
  "required_assurance",
  "reward_amount",
] as const;

// Request-optional (section 2.1); a constant or assigned field — chain,
// domain_tag, fee_amount, salt — is an unknown key and fails hasExactKeys.
const POLICY_OPTIONAL_KEYS = ["cluster", "settlement_mint"] as const;

const ITEM_KEYS = ["prompt", "required", "type"] as const;

export interface ExtractedCreateBody {
  idempotencyKey: string;
  title: string;
  category: string;
  policy: ValidatedPolicyInput;
}

export function extractCreateBody(body: unknown): ExtractedCreateBody | null {
  if (!isPlainObject(body)) return null;
  // Exactly the four keys: a fifth key is a failure, not silently ignored.
  if (!hasExactKeys(body, BODY_KEYS)) return null;

  const idempotencyKey = body["idempotency_key"];
  if (typeof idempotencyKey !== "string" || !UUID_FORM.test(idempotencyKey)) {
    return null;
  }
  const title = body["title"];
  if (typeof title !== "string") return null;
  const category = body["category"];
  if (typeof category !== "string") return null;

  const policy = body["policy"];
  if (!isPlainObject(policy)) return null;
  if (!hasExactKeys(policy, POLICY_REQUIRED_KEYS, POLICY_OPTIONAL_KEYS)) {
    return null;
  }

  const acceptanceWindowSeconds = policy["acceptance_window_seconds"];
  const attesterPubkey = policy["attester_pubkey"];
  const captureRadiusM = policy["capture_radius_m"];
  const challengeWindowSeconds = policy["challenge_window_seconds"];
  const completionWindowSeconds = policy["completion_window_seconds"];
  const evidenceRequirements = policy["evidence_requirements"];
  const lat = policy["lat"];
  const lon = policy["lon"];
  const requiredAssurance = policy["required_assurance"];
  const rewardAmount = policy["reward_amount"];
  if (!isSafeInteger(acceptanceWindowSeconds)) return null;
  if (typeof attesterPubkey !== "string") return null;
  if (!isSafeInteger(captureRadiusM)) return null;
  if (!isSafeInteger(challengeWindowSeconds)) return null;
  if (!isSafeInteger(completionWindowSeconds)) return null;
  if (!Array.isArray(evidenceRequirements)) return null;
  if (typeof lat !== "string") return null;
  if (typeof lon !== "string") return null;
  if (!isSafeInteger(requiredAssurance)) return null;
  if (typeof rewardAmount !== "string") return null;

  // Optional keys: absent is fine; present demands a string. JSON.parse
  // never yields undefined for a present key, so `in` distinguishes.
  let cluster: string | undefined;
  if ("cluster" in policy) {
    const value = policy["cluster"];
    if (typeof value !== "string") return null;
    cluster = value;
  }
  let settlementMint: string | undefined;
  if ("settlement_mint" in policy) {
    const value = policy["settlement_mint"];
    if (typeof value !== "string") return null;
    settlementMint = value;
  }

  // Section 2.2: exactly prompt, required and type per request item — a
  // client-sent id is an unknown key. List count bounds are step 5, not
  // here; a non-boolean required is this step's type failure (D63).
  const items: Array<{ prompt: string; required: boolean; type: string }> = [];
  for (const item of evidenceRequirements) {
    if (!isPlainObject(item)) return null;
    if (!hasExactKeys(item, ITEM_KEYS)) return null;
    const prompt = item["prompt"];
    const required = item["required"];
    const type = item["type"];
    if (typeof prompt !== "string") return null;
    if (typeof required !== "boolean") return null;
    if (typeof type !== "string") return null;
    items.push({ prompt, required, type });
  }

  return {
    idempotencyKey,
    title,
    category,
    policy: {
      acceptanceWindowSeconds,
      attesterPubkey,
      captureRadiusM,
      challengeWindowSeconds,
      cluster,
      completionWindowSeconds,
      evidenceRequirements: items,
      lat,
      lon,
      requiredAssurance,
      rewardAmount,
      settlementMint,
    },
  };
}
