// One dark stylesheet for every screen. Brand palette (navy #10102a, purple accent).
import { StyleSheet } from 'react-native';

export const colors = {
  background: '#10102a',
  surface: '#17173a',
  surfaceHigh: '#1d1d45',
  border: '#2e2e5c',
  text: '#ecebf7',
  label: '#a9a8c8',
  muted: '#8a89ad',
  accent: '#6a59f0',
  accentText: '#9c90ff',
  input: '#0b0b20',
  notice: '#ffd166',
} as const;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  title: { color: colors.text, fontSize: 20, fontWeight: '700', marginBottom: 12 },
  label: { color: colors.label, fontSize: 13, marginTop: 12, marginBottom: 4 },
  value: { color: colors.text, fontSize: 15, marginBottom: 2 },
  muted: { color: colors.muted, fontSize: 13, marginBottom: 6 },
  input: {
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  buttons: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12, marginBottom: 12 },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingVertical: 13,
    paddingHorizontal: 18,
  },
  buttonSecondary: { backgroundColor: colors.surfaceHigh },
  buttonDisabled: { backgroundColor: '#2a2950' },
  buttonPressed: { opacity: 0.7 },
  buttonLabel: { color: '#ffffff', fontSize: 15, fontWeight: '600' },
  chipRow: { flexDirection: 'row', gap: 8 },
  chip: {
    backgroundColor: colors.surfaceHigh,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  chipSelected: { backgroundColor: colors.accent },
  log: {
    flex: 1,
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    minHeight: 120,
  },
  logContent: { padding: 10 },
  placeholder: { color: colors.muted, fontFamily: 'monospace', fontSize: 12 },
  line: { color: '#d6d5ea', fontFamily: 'monospace', fontSize: 12, marginBottom: 6 },
  row: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingVertical: 10,
  },
  notice: { color: colors.notice, fontSize: 14, marginTop: 8, marginBottom: 8 },
  // Header: a small back arrow, the title, an optional action on the right.
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, minHeight: 44 },
  headerBack: { width: 44, height: 44, justifyContent: 'center', marginLeft: -8 },
  headerBackLabel: { color: colors.text, fontSize: 30, lineHeight: 34, paddingLeft: 8 },
  headerTitle: { flex: 1, color: colors.text, fontSize: 20, fontWeight: '700' },
  headerAction: { minWidth: 44, height: 44, justifyContent: 'center', alignItems: 'flex-end' },
  headerActionLabel: { color: colors.accentText, fontSize: 15, fontWeight: '600' },
  // Cards and status pills.
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  },
  cardPressed: { opacity: 0.75 },
  cardTitle: { color: colors.text, fontSize: 17, fontWeight: '700', flex: 1, marginRight: 12 },
  cardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  reward: { color: colors.accentText, fontSize: 20, fontWeight: '800' },
  rewardLarge: { color: colors.text, fontSize: 34, fontWeight: '800' },
  meta: { color: colors.label, fontSize: 14, marginTop: 6 },
  section: { color: colors.label, fontSize: 13, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  pill: { alignSelf: 'flex-start', borderRadius: 999, paddingVertical: 4, paddingHorizontal: 10 },
  pillLabel: { fontSize: 12, fontWeight: '700', letterSpacing: 0.5 },
  toggle: { paddingVertical: 10 },
  toggleLabel: { color: colors.muted, fontSize: 13 },
});
